### ISSUE TITLE
Product sorting

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#77]
Sorting function must sort all products in store not only for current page.

Example (lowest price -> Highest price):
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/10f07c4b-bf24-49f3-8328-01cf70e6eb5f)
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/1afb9a3b-219c-4ed8-b722-5778fb26750c)

**Comment by John-zaviago** [comment]
- this can be a big issue - need to check api to confirm if it a big issue or not

**Comment by chomchuen** [comment]
**Product Search**

I was searching for 'Cake,' but the system only searched for products on the current page, not all the products in the store.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/24965fdd-f7cb-41dc-809a-efa1940a63d4)
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/fea0fafe-f6fe-4052-9ba6-37b46f5aaf6c)
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/1ec214a4-3f20-4c70-867c-6c446fad638b)

**Comment by AnatholyB1** [comment]
I need to speak a little bit with nabeel but i believe that 1h is enough @chomchuen  @John-zaviago

**Comment by AnatholyB1** [comment]
@chomchuen this should be working, it might not work  in the 4 sec just after you reload, try to make the research really fast

**Comment by chomchuen** [comment]
Product Searching can search product from all pages✅ but Product sorting still not as expected. @AnatholyB1 
Please check product sorting and could you give me an estimate time to complete again. Thanks

**Comment by AnatholyB1** [comment]
Aaah ok I didn't get the issue right, I'll ask something to nabeel but this should 30min if it's already implemented in the backend @chomchuen
